services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  productcatalogservice:
    build:
      context: ./src/productcatalogservice
    container_name: productcatalogservice
    restart: unless-stopped
    ports:
      - "3550:3550"
    environment:
      DISABLE_PROFILER: ${DISABLE_PROFILER}
      ENABLE_TRACING: ${ENABLE_TRACING}
    networks:
      - microservices-network

  currencyservice:
    build:
      context: ./src/currencyservice
    container_name: currencyservice
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      PORT: 7000
      DISABLE_PROFILER: ${DISABLE_PROFILER}
      ENABLE_TRACING: ${ENABLE_TRACING}
    networks:
      - microservices-network

  cartservice:
    build:
      context: ./src/cartservice/src
    container_name: cartservice
    restart: unless-stopped
    ports:
      - "7070:7070"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: redis:6379
    networks:
      - microservices-network

  shippingservice:
    build:
      context: ./src/shippingservice
    container_name: shippingservice
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - microservices-network

  paymentservice:
    build:
      context: ./src/paymentservice
    container_name: paymentservice
    restart: unless-stopped
    ports:
      - "50052:50051"
    environment:
      PORT: 50051
      DISABLE_PROFILER: ${DISABLE_PROFILER}
      ENABLE_TRACING: ${ENABLE_TRACING}
    networks:
      - microservices-network

  emailservice:
    build:
      context: ./src/emailservice
    container_name: emailservice
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - microservices-network

  recommendationservice:
    build:
      context: ./src/recommendationservice
    container_name: recommendationservice
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
    networks:
      - microservices-network

  adservice:
    build:
      context: ./src/adservice
    container_name: adservice
    restart: unless-stopped
    ports:
      - "9555:9555"
    networks:
      - microservices-network

  # shoppingassistantservice:
  #   build:
  #     context: ./src/shoppingassistantservice
  #   container_name: shoppingassistantservice
  #   restart: unless-stopped
  #   ports:
  #     - "8083:8080"
  #   networks:
  #     - microservices-network

  checkoutservice:
    build:
      context: ./src/checkoutservice
    container_name: checkoutservice
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      PAYMENT_SERVICE_ADDR: paymentservice:50051
      EMAIL_SERVICE_ADDR: emailservice:8080
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
    networks:
      - microservices-network

  frontend:
    build:
      context: ./src/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - recommendationservice
      - shippingservice
      - checkoutservice
      - adservice
      - paymentservice
      - emailservice
      # - shoppingassistantservice
    environment:
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
      RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      CHECKOUT_SERVICE_ADDR: checkoutservice:5050
      AD_SERVICE_ADDR: adservice:9555
      PAYMENT_SERVICE_ADDR: paymentservice:50051
      EMAIL_SERVICE_ADDR: emailservice:8080
      SHOPPING_ASSISTANT_SERVICE_ADDR: localhost:8080
      DISABLE_PROFILER: ${DISABLE_PROFILER}
      ENABLE_TRACING: ${ENABLE_TRACING}
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge