apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-platform-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/prasadnar100699/cloud-native-microservices-platform.git'
    targetRevision: main
    path: helm/microservices-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true